// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: first.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Docavailable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsTrue bool `protobuf:"varint,1,opt,name=is_true,json=isTrue,proto3" json:"is_true,omitempty"`
}

func (x *Docavailable) Reset() {
	*x = Docavailable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_first_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Docavailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Docavailable) ProtoMessage() {}

func (x *Docavailable) ProtoReflect() protoreflect.Message {
	mi := &file_first_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Docavailable.ProtoReflect.Descriptor instead.
func (*Docavailable) Descriptor() ([]byte, []int) {
	return file_first_proto_rawDescGZIP(), []int{0}
}

func (x *Docavailable) GetIsTrue() bool {
	if x != nil {
		return x.IsTrue
	}
	return false
}

type Serverrespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Off string `protobuf:"bytes,1,opt,name=off,proto3" json:"off,omitempty"`
}

func (x *Serverrespond) Reset() {
	*x = Serverrespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_first_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Serverrespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Serverrespond) ProtoMessage() {}

func (x *Serverrespond) ProtoReflect() protoreflect.Message {
	mi := &file_first_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Serverrespond.ProtoReflect.Descriptor instead.
func (*Serverrespond) Descriptor() ([]byte, []int) {
	return file_first_proto_rawDescGZIP(), []int{1}
}

func (x *Serverrespond) GetOff() string {
	if x != nil {
		return x.Off
	}
	return ""
}

type Docinfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAvail bool `protobuf:"varint,1,opt,name=is_avail,json=isAvail,proto3" json:"is_avail,omitempty"`
}

func (x *Docinfo) Reset() {
	*x = Docinfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_first_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Docinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Docinfo) ProtoMessage() {}

func (x *Docinfo) ProtoReflect() protoreflect.Message {
	mi := &file_first_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Docinfo.ProtoReflect.Descriptor instead.
func (*Docinfo) Descriptor() ([]byte, []int) {
	return file_first_proto_rawDescGZIP(), []int{2}
}

func (x *Docinfo) GetIsAvail() bool {
	if x != nil {
		return x.IsAvail
	}
	return false
}

type Clientmsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clclose bool `protobuf:"varint,1,opt,name=clclose,proto3" json:"clclose,omitempty"`
}

func (x *Clientmsg) Reset() {
	*x = Clientmsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_first_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Clientmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clientmsg) ProtoMessage() {}

func (x *Clientmsg) ProtoReflect() protoreflect.Message {
	mi := &file_first_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clientmsg.ProtoReflect.Descriptor instead.
func (*Clientmsg) Descriptor() ([]byte, []int) {
	return file_first_proto_rawDescGZIP(), []int{3}
}

func (x *Clientmsg) GetClclose() bool {
	if x != nil {
		return x.Clclose
	}
	return false
}

var File_first_proto protoreflect.FileDescriptor

var file_first_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a,
	0x0c, 0x44, 0x6f, 0x63, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x73, 0x5f, 0x74, 0x72, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x69, 0x73, 0x54, 0x72, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x66, 0x66, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x66, 0x66, 0x22, 0x24, 0x0a, 0x07, 0x44, 0x6f, 0x63,
	0x69, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x22,
	0x25, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6c, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63,
	0x6c, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x32, 0x5b, 0x0a, 0x06, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x2b, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4f, 0x6e, 0x12, 0x0d, 0x2e, 0x44,
	0x6f, 0x63, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x0e, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x28, 0x01, 0x12, 0x24, 0x0a,
	0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x0a, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x6d, 0x73, 0x67, 0x1a, 0x08, 0x2e, 0x44, 0x6f, 0x63, 0x69, 0x6e, 0x66,
	0x6f, 0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_first_proto_rawDescOnce sync.Once
	file_first_proto_rawDescData = file_first_proto_rawDesc
)

func file_first_proto_rawDescGZIP() []byte {
	file_first_proto_rawDescOnce.Do(func() {
		file_first_proto_rawDescData = protoimpl.X.CompressGZIP(file_first_proto_rawDescData)
	})
	return file_first_proto_rawDescData
}

var file_first_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_first_proto_goTypes = []interface{}{
	(*Docavailable)(nil),  // 0: Docavailable
	(*Serverrespond)(nil), // 1: Serverrespond
	(*Docinfo)(nil),       // 2: Docinfo
	(*Clientmsg)(nil),     // 3: Clientmsg
}
var file_first_proto_depIdxs = []int32{
	0, // 0: Doctor.DoctorOn:input_type -> Docavailable
	3, // 1: Doctor.ServerSend:input_type -> Clientmsg
	1, // 2: Doctor.DoctorOn:output_type -> Serverrespond
	2, // 3: Doctor.ServerSend:output_type -> Docinfo
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_first_proto_init() }
func file_first_proto_init() {
	if File_first_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_first_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Docavailable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_first_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Serverrespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_first_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Docinfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_first_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Clientmsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_first_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_first_proto_goTypes,
		DependencyIndexes: file_first_proto_depIdxs,
		MessageInfos:      file_first_proto_msgTypes,
	}.Build()
	File_first_proto = out.File
	file_first_proto_rawDesc = nil
	file_first_proto_goTypes = nil
	file_first_proto_depIdxs = nil
}
